- name: copy war file to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy war file
      copy:
        src: "/usr"
        dest: "/opt/tomcat/webapps/.war"
        remote_src: no
        
    - name: restart tomcat
        systemd:
          name: tomcat
          state: restarted
