- name: copy war file to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy war file
      copy:
        src: "/var/snap/jenkins/4874/workspace/sampanisble/target/simpleweb.war"
        dest: "/opt/tomcat/webapps/simpleweb.war"
        remote_src: no
        
    - name: restart tomcat
      systemd:
        name: tomcat
        state: restarted
